### ISSUE TITLE
question: html within template or html-files

### ISSUE THREAD

**Issue by MarioBrendel** [mgechev/angular2-style-guide#2]
Hello mgechev,

i really love your style guide. Especially the part about the inputs and hostbindings within the component. But I'm a little bit curios since your directory structure suggests to have html files, while in the template part you say "Keep the components' templates as lean as possible and inline them inside of the `@Component` decorator". Did i miss something?

**Comment by mgechev** [comment]
Hey @MarioBrendel,

it's good to have your templates in the same file since this way you can easily peek at the component's structure. However, in some cases the templates may get too long and this way you can lose focus of the logic defined in the component's controllers. In such cases the style guide states that it is better to keep the templates in external files.

The directory structure shows a sample application structure where we have examples for both - inline and external templates.
