### ISSUE TITLE
Simplify directory structure

### ISSUE THREAD

**Issue by sonicoder86** [mgechev/angular2-style-guide#51]
If we have a directory for components why is it necessary to suffix every file with `component`?
Seems like a big duplication and doesnt add to understand the files.

The directory by itself describes the type of files residing within it.

**Comment by joshwiens** [comment]
https://github.com/mgechev/angular2-style-guide/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+directory

In particular - the issues around #46

**Comment by sonicoder86** [comment]
Read the reasoning why a similar issue was closed.
The structure in the closing comment though can be made simpler like this
- app
  - login
  - home
    - dashboard
      - dashboard
        - model.ts
        - component.ts
        - template.html
        - style.css
        - reducer.ts
      - gauge
        - component.ts
        - template.html
        - style.css
        - reducer.ts
  - edit-profile

**Comment by joshwiens** [comment]
I guess my point was, this issue has been discussed to death, to include variations on what you are suggesting.
- What exists was chosen because it has a balance between simplicity / scalability / verbosity.
- The facade pattern is something that isn't going to go away in the Angular2 world.

Going "ultra simple" makes for complex problems when you get into bundling / lazy loading, and quite frankly, having X number of component.ts files in an application of any real size isn't going to be doing anyone any favors.
- You can't fuzzy find / search as everything has the same name.
- You can't quickly visually scan the application structure.
- Debugging that would be a nightmare as again, everything has the same name.
- Insert the myriad of pack / load / ship issues listed elsewhere.

All I can see from development to production deployment is simplicity turning into complexity & regret at scale.

Personally, the idea of having my team use any of the super simple patterns that have been suggested over the past few months when converting any of our production applications makes my brain hurt.

**Comment by mgechev** [comment]
@blacksonic has a point. However, I agree that there's some redundancy. We're working on eliminating it as much as possible and having optimal directory structure in terms of verbosity and navigability.

For sure what you see is not the final recommendation.

**Comment by sonicoder86** [comment]
Hope there will be a less redundant structure and then i would be happy to migrate my Angular 2 starter to it
https://github.com/blacksonic/angular2-es6-starter
