### ISSUE TITLE
Avoid using forwardRef considerations

### ISSUE THREAD

**Issue by kamarouski** [mgechev/angular2-style-guide#56]
I didn't find aby mentions of this rule in official styleguide.

https://angular.io/styleguide

There are some cases where we need forwardRef:
1. Resolve cycle dependencies. I know, I know you tell me it's a bad design, but sometimes we do have them. For example when rendering tree structure of similar components (A renders B, B renders A etc.). It's a valid scenario and cannot be ignored.
2. ngModel implementation. It's probably just because I didn't find a better way to implement this. Imagine you need implement custom input component that supports ngModel property (e.g. <my-input [(ngModel)]="value" ></my-input>) To achieve this we need two things:
3. Implement ControlValueAccessor for our component,
4. Create custom Control Value Accessor like

``` ts
export const CSN_MY_INPUT_CONTROL_VALUE_ACCESSOR = new Provider(
    NG_VALUE_ACCESSOR, {
        useExisting: forwardRef(() => MyInputComponent),
        multi: true
    }
);
```

**Comment by mgechev** [comment]
Yes, subset of the styles from this style guide moved to the official one after a lot of discussions and meetings. `forwardRef` is not one of the issues that we agreed to be part of the official style guide.

Since, as mentioned in the readme, this repo is already deprecated, you can join the discussion here https://github.com/angular/angular.io/issues/1151.
